// Code generated by MockGen. DO NOT EDIT.
// Source: internal/balances/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/balances/usecase.go -destination=internal/balances/mocks/mock.go
//
// Package mock_balances is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	balances "github.com/Aleksey-Andris/yandex-gophermart/internal/balances"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockStorage) Get(ctx context.Context, userID int64) (*balances.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(*balances.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorage)(nil).Get), ctx, userID)
}

// Spend mocks base method.
func (m *MockStorage) Spend(ctx context.Context, oper *balances.Operation) (*balances.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Spend", ctx, oper)
	ret0, _ := ret[0].(*balances.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Spend indicates an expected call of Spend.
func (mr *MockStorageMockRecorder) Spend(ctx, oper any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Spend", reflect.TypeOf((*MockStorage)(nil).Spend), ctx, oper)
}
